<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MusikColor.App</RootNamespace>
    <AssemblyName>MusikColor</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.Views.WPF" Version="2.88.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MusikColor.Contracts\MusikColor.Contracts.csproj" />
    <ProjectReference Include="..\MusikColor.Core\MusikColor.Core.csproj" />
    <ProjectReference Include="..\MusikColor.Adapters.Capture\MusikColor.Adapters.Capture.csproj" />
    <ProjectReference Include="..\MusikColor.Adapters.Visualization\MusikColor.Adapters.Visualization.csproj" />
  </ItemGroup>

</Project>
